use_frameworks!

platform :ios, '10.0'

target 'ZHUIMaker_Example' do
  pod 'ZHUIMaker', :path => '../'

  target 'ZHUIMaker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
